spring:
  application:
    name: rating-services
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Ankit@123+
    username: postgres
    url: jdbc:postgresql://localhost:5432/rating_service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true