spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ankit@123+
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
